#!/usr/bin/env python3
"""
detect_inflection.py - Deterministic detection of the AI-tool introduction date.

Writes:
  acceleration/data/inflection.json

Two-candidate algorithm:
  Candidate A: earliest commit with an AI-tool author/co-author trailer.
  Candidate B: sharpest sustained inflection in a rolling 14-day commit-velocity
               series (delta > mean + 2 sigma persisting for >= 3 consecutive
               windows, with the threshold computed from the *prefix* of the
               series so the inflection itself does not contaminate it).

Selection (AAP section 0.3.1.2):
  - Both present AND within 14 days -> choose earlier; method="convergent_evidence"
  - Both present AND farther apart   -> choose Candidate B;  method="single_signal"
  - Only A present                    -> choose A;          method="single_signal"
  - Only B present                    -> choose B;          method="single_signal"
  - Neither present                   -> Insufficient signal

Authority:
  - AAP section 0.3.1   - "build a `detect_inflection` routine that scans every
                         commit's trailers for AI-tool email patterns and, in
                         parallel, computes a rolling 2-week velocity series
                         and identifies the sharpest sustained inflection."
  - AAP section 0.3.1.2 - Inflection Detection Decision Flow.
  - AAP section 0.4.1   - enumerates this file as a CREATE target.

Read-only discipline:
  - No git write operations (no `git add`, `git commit`, `git push`, branch
    creation, or remote write).
  - Filesystem writes confined to a single output file (`inflection.json`).
  - Input reads from either `commits.jsonl` (read-only) or `git log` subprocess
    (read-only).

Invocation:
  python3 acceleration/scripts/detect_inflection.py \\
      --repo-root . \\
      --branch refs/remotes/origin/main \\
      --commits-jsonl acceleration/data/commits.jsonl \\
      --output acceleration/data/inflection.json
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# AI-tool author/co-author email patterns enumerated in AAP section 0.3.1.
# These are matched both as direct author emails (Candidate A path #1) and
# as substrings inside `Co-authored-by:` trailers (Candidate A path #2).
# The four explicit pattern hooks are:
#   * agent@blitzy.com       - Blitzy Agent canonical email (the dominant
#                              after-period actor in the Formbricks repo)
#   * noreply@anthropic.com  - Claude Code attributions
#   * copilot@github.com     - GitHub Copilot attributions
#   * blitzy[bot]            - Blitzy GitHub App bot account; matched by
#                              substring because emails for GitHub App bots
#                              are autogenerated (e.g.
#                              <id>+blitzy[bot]@users.noreply.github.com)
AI_EMAILS: tuple[str, ...] = (
    "agent@blitzy.com",
    "noreply@anthropic.com",
    "copilot@github.com",
)

# Pre-compiled regex patterns scanning the commit body and trailer block for
# AI co-author signals. The patterns are case-insensitive and tolerant of
# whitespace around the angle-bracketed email. The fourth pattern matches
# the `blitzy[bot]` GitHub App identity by its display name because its
# email is autogenerated.
AI_TRAILER_RES: tuple[re.Pattern[str], ...] = (
    re.compile(r"Co-authored-by:[^<\n]*<\s*(agent@blitzy\.com)\s*>", re.IGNORECASE),
    re.compile(r"Co-authored-by:[^<\n]*<\s*(noreply@anthropic\.com)\s*>", re.IGNORECASE),
    re.compile(r"Co-authored-by:[^<\n]*<\s*(copilot@github\.com)\s*>", re.IGNORECASE),
    re.compile(r"Co-authored-by:[^<\n]*\bblitzy\[bot\]", re.IGNORECASE),
)

# Velocity-series parameters fixed by AAP section 0.3.1.2:
#   * 14-day rolling windows aligned to Mondays in UTC.
#   * Sustained inflection threshold = prefix mean + 2.0 * prefix stdev.
#   * Sustained run length = 3 consecutive windows (>=6 weeks of elevation).
#   * Convergence horizon = 14 days (Candidates A and B treated as the same
#     event when the gap between them is at most this many days).
ROLLING_WINDOW_DAYS: int = 14
INFLECTION_SIGMA: float = 2.0
INFLECTION_MIN_RUN_WINDOWS: int = 3
CONVERGENCE_HORIZON_DAYS: int = 14


# ---------------------------------------------------------------------------
# Commit dataclass and timestamp parsing
# ---------------------------------------------------------------------------


@dataclass
class Commit:
    """A single commit record consumed by the inflection detector.

    Attributes
    ----------
    sha
        40-character commit SHA-1 in lowercase hex.
    author_email
        Lowercased author email address (the `%aE` placeholder in
        `git log --format`).
    author_date
        ISO-8601 author timestamp (the `%aI` placeholder). May be empty
        when read from a corrupt `commits.jsonl` line.
    body
        Commit message body (everything after the subject line) used by
        :func:`is_ai_signal` to scan for AI co-author trailers.
    trailers
        Pre-extracted trailer lines from `%(trailers:only,unfold)`. When the
        commit is loaded from `commits.jsonl`, this field carries whatever
        the upstream extractor produced; when loaded from live `git log`,
        each non-blank trailer line becomes one element.
    ai_signal_precomputed
        Optional `bool` set by an upstream extractor (`extract_git.py`) when
        the commit has already been scanned. When ``True``, :func:`is_ai_signal`
        short-circuits to ``True`` without re-scanning. When ``False`` or
        ``None``, the scan runs in full.
    """

    sha: str
    author_email: str
    author_date: str
    body: str = ""
    trailers: list[str] = field(default_factory=list)
    ai_signal_precomputed: bool | None = None

    def author_dt(self) -> datetime:
        """Return the parsed author timestamp as a timezone-aware UTC datetime."""

        return parse_iso(self.author_date)


def parse_iso(s: str) -> datetime:
    """Parse an ISO-8601 timestamp string and normalise it to UTC.

    Handles the three forms observed in practice:
      1. Canonical ISO with offset, e.g. ``2026-02-25T13:45:12+00:00``.
      2. Canonical ISO with the ``Z`` UTC suffix, e.g.
         ``2026-02-25T13:45:12Z`` (rewritten to ``+00:00`` before parsing
         because :func:`datetime.fromisoformat` did not accept ``Z`` until
         Python 3.11).
      3. The compact offset form some older `git` versions emit,
         e.g. ``2026-02-25T13:45:12+0000`` (no colon in the offset). A
         fallback regex repairs the offset before parsing.

    Naive timestamps are interpreted as UTC. Failures return the Unix
    epoch in UTC so the rest of the pipeline never crashes on a malformed
    line; the inflection detector treats epoch-anchored commits as never
    matching the AI signal because they sort to the very beginning of
    history.
    """

    if not s:
        return datetime(1970, 1, 1, tzinfo=timezone.utc)
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
    except ValueError:
        # Older git versions emit `+0000` without a colon; ISO requires
        # `+00:00`. Rewrite the offset and retry once.
        m = re.match(
            r"^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})([+-]\d{2})(\d{2})$",
            s,
        )
        if m:
            try:
                dt = datetime.fromisoformat(
                    f"{m.group(1)}{m.group(2)}:{m.group(3)}"
                )
            except ValueError:
                return datetime(1970, 1, 1, tzinfo=timezone.utc)
        else:
            return datetime(1970, 1, 1, tzinfo=timezone.utc)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


# ---------------------------------------------------------------------------
# Data-source readers (JSONL OR live git)
# ---------------------------------------------------------------------------


def iter_commits_from_jsonl(path: Path) -> Iterator[Commit]:
    """Stream :class:`Commit` records from a line-delimited JSON file.

    Each non-blank line is decoded as a JSON object; the recognised keys
    are ``sha``, ``author_email``, ``author_date``, ``body``, ``trailers``,
    and ``ai_signal``. Unknown keys are ignored so this reader stays
    forward-compatible with the upstream ``extract_git.py`` schema.

    Malformed JSON lines are silently skipped; the detector remains robust
    in the face of a truncated extractor output and the line that failed
    can be diagnosed downstream via the line-count reported in the
    detector's INFO log.
    """

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                # Tolerate partial writes from a previous interrupted
                # extraction; keep streaming the rest of the file.
                continue
            yield Commit(
                sha=rec.get("sha") or "",
                author_email=(rec.get("author_email") or "").lower(),
                author_date=rec.get("author_date") or "",
                body=rec.get("body") or "",
                trailers=list(rec.get("trailers") or []),
                ai_signal_precomputed=rec.get("ai_signal"),
            )


def iter_commits_from_git(repo_root: Path, ref: str) -> Iterator[Commit]:
    """Stream :class:`Commit` records by invoking ``git log`` directly.

    Used when ``commits.jsonl`` is unavailable so the script remains
    usable in isolation (for example, by an operator running it before
    ``extract_git.py`` has executed). Reads only -- never modifies the
    repository.

    The record separator is ASCII RS (`\\x1e`) and the unit separator is
    ASCII US (`\\x1f`); both are control characters that cannot appear
    inside commit metadata, eliminating ambiguity around bodies that
    contain newlines or angle brackets.

    Parameters
    ----------
    repo_root
        Directory in which `git` runs. Should resolve to a git working
        tree.
    ref
        The git ref to walk. Typically ``refs/remotes/origin/main`` for
        the canonical history; ``HEAD`` as a fallback.

    Yields
    ------
    Commit
        One record per commit reachable from ``ref``, in `git log` order
        (newest first). The detector consumes the iterator into a list
        so order does not matter for the algorithm.
    """

    fmt = "%H\x1f%aE\x1f%aI\x1f%b\x1f%(trailers:only,unfold)\x1e"
    proc = subprocess.Popen(
        ["git", "log", ref, f"--format={fmt}"],
        cwd=str(repo_root),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    assert proc.stdout is not None  # subprocess.PIPE -> non-None per spec
    buf = ""
    try:
        while True:
            chunk_bytes = proc.stdout.read(65536)
            if not chunk_bytes:
                break
            buf += chunk_bytes.decode("utf-8", errors="replace")
            while "\x1e" in buf:
                rec, buf = buf.split("\x1e", 1)
                # `git log` appends `\n` after each `%format` template,
                # leaving a leading newline at the start of every record
                # after the first. Strip it for clean parsing.
                rec = rec.lstrip("\n")
                if not rec:
                    continue
                # The body may itself contain newlines (multi-paragraph
                # commit messages) but cannot contain the US separator,
                # so `split("\x1f")` is unambiguous when followed by the
                # 5-field guard below.
                parts = rec.split("\x1f")
                if len(parts) < 5:
                    continue
                yield Commit(
                    sha=parts[0],
                    author_email=parts[1].lower(),
                    author_date=parts[2],
                    body=parts[3],
                    trailers=[t for t in parts[4].splitlines() if t.strip()],
                )
    finally:
        # Cleanly release both pipes and reap the child process. The
        # `wait(timeout=30)` is a safety net: `git log` always exits on
        # its own once stdout is drained, so 30 s is far beyond any
        # plausible blocking.
        try:
            proc.stdout.close()
        except Exception:  # pragma: no cover - defensive cleanup
            pass
        if proc.stderr is not None:
            try:
                proc.stderr.close()
            except Exception:  # pragma: no cover - defensive cleanup
                pass
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:  # pragma: no cover - defensive
            proc.kill()
            proc.wait()


# ---------------------------------------------------------------------------
# Candidate A: earliest commit with an AI-tool author/co-author signal
# ---------------------------------------------------------------------------


def is_ai_signal(commit: Commit) -> tuple[bool, list[str]]:
    """Return whether ``commit`` carries an AI-tool attribution and the indicators.

    The function checks three sources:
      1. ``commit.ai_signal_precomputed`` (when ``True``, short-circuits
         immediately; this honours an upstream extractor that has already
         performed the scan).
      2. ``commit.author_email`` against :data:`AI_EMAILS` (case-insensitive).
      3. The concatenation of ``commit.body`` and ``commit.trailers``
         against :data:`AI_TRAILER_RES`.

    Returns
    -------
    tuple[bool, list[str]]
        ``(True, ["author_email=...", "trailer=..."])`` when at least one
        signal fired; ``(False, [])`` otherwise. The indicator strings are
        truncated to 120 characters for the inflection-output payload.
    """

    if commit.ai_signal_precomputed is True:
        return True, ["precomputed_from_jsonl"]

    indicators: list[str] = []
    if commit.author_email.lower() in AI_EMAILS:
        indicators.append(f"author_email={commit.author_email}")

    # Concatenate body and trailers into a single haystack so a co-author
    # trailer that landed in either place (some git versions split them)
    # still matches. The newline join preserves line-anchored semantics
    # for the regexes (which expect "Co-authored-by:" at the start of a
    # line).
    text = "\n".join([commit.body] + commit.trailers)
    for pat in AI_TRAILER_RES:
        m = pat.search(text)
        if m:
            indicators.append(f"trailer={m.group(0)[:120]}")

    return bool(indicators), indicators


def find_candidate_a(commits: Iterable[Commit]) -> dict[str, Any] | None:
    """Find the earliest commit carrying an AI co-author/author signal.

    Iterates ``commits`` once, tracking the earliest commit (by author
    timestamp) for which :func:`is_ai_signal` returns ``True``. Returns
    a serialisable description suitable for embedding into the inflection
    JSON output.

    Returns
    -------
    dict[str, Any] | None
        A payload describing Candidate A, or ``None`` when no commit in
        ``commits`` matches any AI pattern.
    """

    earliest: tuple[datetime, Commit, list[str]] | None = None
    for c in commits:
        ok, indicators = is_ai_signal(c)
        if not ok:
            continue
        dt = c.author_dt()
        if earliest is None or dt < earliest[0]:
            earliest = (dt, c, indicators)

    if earliest is None:
        return None

    dt, c, indicators = earliest
    # `asdict(c)` produces a flat dictionary that the downstream renderers
    # can echo verbatim into the report's Methodology section. This gives
    # complete provenance for the chosen Candidate A commit, satisfying
    # the Reproducibility rule (every number traceable to a raw record).
    return {
        "candidate": "A",
        "date": dt.date().isoformat(),
        "datetime": dt.isoformat(),
        "commit_sha": c.sha,
        "author_email": c.author_email,
        "indicators": indicators,
        "commit_record": asdict(c),
        "description": "Earliest commit with AI co-author trailer or AI author email.",
    }



# ---------------------------------------------------------------------------
# Candidate B: sharpest sustained velocity inflection
# ---------------------------------------------------------------------------


def monday_floor(d: date) -> date:
    """Return the most recent Monday on or before ``d``.

    Python's :meth:`date.weekday` returns 0 for Monday, so subtracting
    that value gives the Monday of the same ISO week.
    """

    return d - timedelta(days=d.weekday())


def bucket_to_window_start(d: date) -> date:
    """Return the start date of the 14-day Monday-aligned window containing ``d``.

    The windowing is anchored at ``2000-01-03`` (a Monday) so that two
    machines running the analysis at different times produce bit-identical
    window assignments for any given commit. Without an anchor, the
    window grid would shift with the head-date.

    Walking through the math: take the Monday of ``d``'s week, compute its
    distance in days from the epoch Monday, then subtract whatever portion
    of that distance is "into" the current 14-day window (the modulo).
    """

    md = monday_floor(d)
    epoch = date(2000, 1, 3)  # Monday immediately following the Year 2000 weekend
    days_since = (md - epoch).days
    return md - timedelta(days=days_since % ROLLING_WINDOW_DAYS)


def daily_commit_counts(commits: Iterable[Commit]) -> dict[date, int]:
    """Aggregate commits by their author-timestamp UTC calendar date.

    The author date (not the committer date) is used so that rebases and
    cherry-picks land on the same day they were originally written; this
    is the date that human readers associate with the work being done.
    """

    counts: dict[date, int] = {}
    for c in commits:
        d = c.author_dt().date()
        counts[d] = counts.get(d, 0) + 1
    return counts


def rolling_velocity_series(counts: dict[date, int]) -> list[tuple[date, int]]:
    """Return non-overlapping 14-day buckets across the observed range.

    The series is built across the closed interval [min observed date,
    max observed date] in :data:`ROLLING_WINDOW_DAYS` steps, with each
    bucket's count being the sum of daily commit counts within the
    14-day span. Buckets with no commits are kept (count 0) so the
    inflection algorithm sees a uniform time axis.

    Parameters
    ----------
    counts
        Mapping from calendar date to commit count, as produced by
        :func:`daily_commit_counts`.

    Returns
    -------
    list[tuple[date, int]]
        ``[(window_start, count_in_window), ...]`` in chronological
        order. Empty when ``counts`` is empty.
    """

    if not counts:
        return []
    sorted_dates = sorted(counts.keys())
    start = sorted_dates[0]
    end = sorted_dates[-1]
    series: list[tuple[date, int]] = []
    cur = bucket_to_window_start(start)
    while cur <= end:
        total = 0
        for offset in range(ROLLING_WINDOW_DAYS):
            d = cur + timedelta(days=offset)
            total += counts.get(d, 0)
        series.append((cur, total))
        cur += timedelta(days=ROLLING_WINDOW_DAYS)
    return series


def find_candidate_b(series: list[tuple[date, int]]) -> dict[str, Any] | None:
    """Find the sharpest sustained inflection in a velocity series.

    Algorithm (AAP section 0.3.1.2):
      For each candidate window index ``i``:
        1. Compute the *prefix* mean and sample standard deviation over
           ``series[:i]`` (i.e. windows *before* the candidate). Using
           the prefix prevents the inflection itself from inflating
           ``sigma`` and thereby hiding itself.
        2. Form the threshold ``prefix_mean + INFLECTION_SIGMA * prefix_std``.
        3. Check whether all windows in ``series[i : i + MIN_RUN_WINDOWS]``
           exceed the threshold (the "sustained" requirement).
        4. If yes, record the candidate with a "sharpness" score equal to
           the median window count over the sustained run; higher score
           wins.

    Sample-variance Bessel correction (``/ (n-1)``) is used because the
    prefix is a sample of the broader pre-introduction population, not
    the population itself. With only two prefix windows, the divisor is
    one (``max(n-1, 1)``) which yields the squared deviation - the
    correct two-sample variance.

    Returns
    -------
    dict[str, Any] | None
        The strongest candidate (highest median run-count, earliest index
        on ties), or ``None`` when no sustained inflection passes the
        threshold or when there are not enough windows to evaluate at all.
    """

    # Need >= MIN_RUN windows to satisfy the run-length test, AND >= 2
    # windows of prefix for sample variance, so >= MIN_RUN + 2 in total.
    if len(series) < INFLECTION_MIN_RUN_WINDOWS + 2:
        return None

    candidates: list[tuple[int, float, float]] = []  # (index, score, prefix_std)
    for i in range(2, len(series) - INFLECTION_MIN_RUN_WINDOWS + 1):
        prefix = [s[1] for s in series[:i]]
        prefix_mean = sum(prefix) / len(prefix)
        # Sample variance with Bessel correction; clamp the divisor to 1
        # so it never becomes zero (only relevant defensively because the
        # i>=2 loop guard already ensures len(prefix) >= 2).
        prefix_var = sum((x - prefix_mean) ** 2 for x in prefix) / max(
            len(prefix) - 1, 1
        )
        prefix_std = math.sqrt(prefix_var)
        threshold = prefix_mean + INFLECTION_SIGMA * prefix_std
        window_slice = series[i : i + INFLECTION_MIN_RUN_WINDOWS]
        if all(w[1] > threshold for w in window_slice):
            # "Sharpest" tie-break: median count over the run. Median is
            # more robust than mean against a single huge spike inside an
            # otherwise modest run.
            sorted_counts = sorted(w[1] for w in window_slice)
            score = sorted_counts[len(sorted_counts) // 2]
            candidates.append((i, float(score), prefix_std))

    if not candidates:
        return None

    # Highest score wins; ties resolve to the earliest window (the first
    # window where the elevation began).
    candidates.sort(key=lambda t: (-t[1], t[0]))
    i, score, prefix_std = candidates[0]
    window_start = series[i][0]
    return {
        "candidate": "B",
        "date": window_start.isoformat(),
        "window_start_date": window_start.isoformat(),
        "window_count": series[i][1],
        "prefix_mean": sum(s[1] for s in series[:i]) / i,
        "prefix_std": prefix_std,
        "sigma_threshold": INFLECTION_SIGMA,
        "min_run_windows": INFLECTION_MIN_RUN_WINDOWS,
        "score_median_in_run": score,
        "description": "Sharpest sustained inflection in the rolling 14-day commit velocity series.",
    }



# ---------------------------------------------------------------------------
# Selection logic
# ---------------------------------------------------------------------------


def days_between(a_iso: str, b_iso: str) -> int:
    """Return the absolute number of calendar days between two ISO-8601 dates.

    Both arguments must be of the form ``YYYY-MM-DD``. Used to evaluate
    the convergence horizon between Candidates A and B.
    """

    return abs((date.fromisoformat(a_iso) - date.fromisoformat(b_iso)).days)


def select_inflection(
    cand_a: dict[str, Any] | None,
    cand_b: dict[str, Any] | None,
) -> dict[str, Any]:
    """Apply AAP section 0.3.1.2 selection rules to combine candidates.

    Decision matrix
    ---------------

    +---------------+---------------+-----------+--------------------------------+
    | Candidate A   | Candidate B   | gap days  | Outcome                        |
    +===============+===============+===========+================================+
    | None          | None          | -         | Insufficient signal            |
    +---------------+---------------+-----------+--------------------------------+
    | present       | present       | <= 14     | earlier of A/B, "convergent"   |
    +---------------+---------------+-----------+--------------------------------+
    | present       | present       | >  14     | B wins, "single_signal"        |
    +---------------+---------------+-----------+--------------------------------+
    | present       | None          | -         | A wins, "single_signal"        |
    +---------------+---------------+-----------+--------------------------------+
    | None          | present       | -         | B wins, "single_signal"        |
    +---------------+---------------+-----------+--------------------------------+

    The diverged-pair rule prefers Candidate B because the velocity
    inflection is the *data-driven* signal: a single ceremonial AI
    co-author trailer can mark a date weeks before sustained AI work
    actually begins.

    Returns
    -------
    dict[str, Any]
        The complete result object that becomes the body of
        ``inflection.json``. Always carries:

          * ``found``           - bool
          * ``method``          - ``None`` | ``"convergent_evidence"`` | ``"single_signal"``
          * ``candidates``      - both A and B verbatim (one may be ``None``)
          * ``rationale``       - human-readable reasoning (when found)
          * ``date``            - chosen date (when found)
          * ``chosen_candidate``- ``"A"`` | ``"B"`` (when found)
          * ``value`` / ``needed`` - Insufficient-signal explanation (when not found)
    """

    # Case 1: neither candidate detected -> Insufficient signal.
    if cand_a is None and cand_b is None:
        return {
            "found": False,
            "value": "Insufficient signal — no AI introduction detected",
            "method": None,
            "candidates": {"A": None, "B": None},
            "needed": (
                "Either at least one commit with an AI co-author trailer / "
                "AI author email, OR a sustained inflection in commit velocity "
                "exceeding 2 sigma for >= 3 windows."
            ),
        }

    # Case 2: both candidates detected.
    if cand_a is not None and cand_b is not None:
        gap = days_between(cand_a["date"], cand_b["date"])
        if gap <= CONVERGENCE_HORIZON_DAYS:
            # Convergent: pick the earlier of the two so we capture the
            # earliest evidence of the introduction event.
            chosen = cand_a if cand_a["date"] <= cand_b["date"] else cand_b
            return {
                "found": True,
                "date": chosen["date"],
                "method": "convergent_evidence",
                "convergence_gap_days": gap,
                "candidates": {"A": cand_a, "B": cand_b},
                "chosen_candidate": chosen["candidate"],
                "rationale": (
                    f"Candidates A ({cand_a['date']}) and B ({cand_b['date']}) "
                    f"are {gap} days apart (within the "
                    f"{CONVERGENCE_HORIZON_DAYS}-day convergence horizon); "
                    f"selected the earlier."
                ),
            }
        # Divergent pair -> Candidate B is the data-driven fallback.
        return {
            "found": True,
            "date": cand_b["date"],
            "method": "single_signal",
            "convergence_gap_days": gap,
            "candidates": {"A": cand_a, "B": cand_b},
            "chosen_candidate": "B",
            "rationale": (
                f"Candidates A ({cand_a['date']}) and B ({cand_b['date']}) "
                f"diverge by {gap} days (exceeds the "
                f"{CONVERGENCE_HORIZON_DAYS}-day convergence horizon); "
                f"selected Candidate B (data-driven) per AAP §0.3.1.2 "
                f"fallback rule."
            ),
        }

    # Case 3: only Candidate A present.
    if cand_a is not None:
        return {
            "found": True,
            "date": cand_a["date"],
            "method": "single_signal",
            "candidates": {"A": cand_a, "B": None},
            "chosen_candidate": "A",
            "rationale": "Only Candidate A (AI co-author trailer / author email) was detected.",
        }

    # Case 4: only Candidate B present.
    # The conditional branches above guarantee cand_b is not None here.
    assert cand_b is not None
    return {
        "found": True,
        "date": cand_b["date"],
        "method": "single_signal",
        "candidates": {"A": None, "B": cand_b},
        "chosen_candidate": "B",
        "rationale": "Only Candidate B (sustained velocity inflection) was detected.",
    }



# ---------------------------------------------------------------------------
# CLI: argparse and main entry point
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Define and parse the script's command-line arguments.

    Flags
    -----
    --repo-root
        Path to the git working tree. Used only when ``commits.jsonl``
        is absent (live-git fallback). Defaults to the current directory.
    --branch
        Git ref to walk in the live-git fallback. When omitted, the
        script prefers ``refs/remotes/origin/main`` if it exists, else
        ``HEAD``.
    --commits-jsonl
        Path to the line-delimited JSON file produced by
        ``extract_git.py``. When this file exists and is non-empty,
        the script reads from it instead of invoking ``git log``.
    --output
        Destination path for ``inflection.json``. Parent directories are
        created on demand.
    """

    p = argparse.ArgumentParser(
        description="Detect the AI-tool introduction inflection date.",
    )
    p.add_argument(
        "--repo-root",
        type=Path,
        default=Path("."),
        help="Path to the git working tree (default: %(default)s).",
    )
    p.add_argument(
        "--branch",
        default=None,
        help=(
            "Git ref used by the live-git fallback when commits.jsonl is "
            "absent (default: prefer refs/remotes/origin/main, else HEAD)."
        ),
    )
    p.add_argument(
        "--commits-jsonl",
        type=Path,
        default=Path("acceleration/data/commits.jsonl"),
        help=(
            "Path to commits.jsonl produced by extract_git.py "
            "(default: %(default)s)."
        ),
    )
    p.add_argument(
        "--output",
        type=Path,
        default=Path("acceleration/data/inflection.json"),
        help="Destination for inflection.json (default: %(default)s).",
    )
    return p.parse_args(argv)


def _resolve_live_git_ref(repo_root: Path, requested: str | None) -> str:
    """Pick the ref the live-git fallback should walk.

    Resolution order:
      1. The explicit ``--branch`` value when provided by the caller.
      2. ``refs/remotes/origin/main`` when it exists (canonical history
         on this monorepo).
      3. ``HEAD`` as the final fallback.
    """

    if requested:
        return requested
    try:
        subprocess.run(
            ["git", "rev-parse", "--verify", "refs/remotes/origin/main"],
            cwd=str(repo_root),
            capture_output=True,
            check=True,
        )
        return "refs/remotes/origin/main"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "HEAD"


def main(argv: list[str] | None = None) -> int:
    """Run the inflection-detection pipeline.

    The function is intentionally non-fatal: even when no signal is
    detected, it writes an Insufficient-signal payload to the output
    path and exits ``0``. The orchestrator inspects the JSON contents to
    decide whether to continue or to short-circuit.

    Parameters
    ----------
    argv
        Command-line arguments excluding the program name. ``None`` (the
        default) reads :data:`sys.argv`.

    Returns
    -------
    int
        Process exit code. ``0`` on success (including the
        "Insufficient signal" branch); ``1`` if an unexpected I/O error
        prevents writing the output file.
    """

    args = parse_args(argv)

    # Deferred import of the structured logger so the script can still
    # run on a path where the `acceleration` package is not yet importable.
    # AAP Rule 1 (Observability) mandates correlation-ID-tagged JSON logs;
    # the fallback is stdlib logging so the operator still sees output.
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
        from acceleration.observability.logger import (  # noqa: WPS433
            generate_run_id,
            get_logger,
        )

        run_id = os.environ.get("ACCEL_RUN_ID") or generate_run_id()
        log = get_logger("acceleration.scripts.detect_inflection", run_id=run_id)
    except Exception:  # pragma: no cover - exercised only on broken installs
        import logging

        logging.basicConfig(
            level=os.environ.get("ACCEL_LOG_LEVEL", "INFO"),
            format="%(asctime)s %(levelname)s %(name)s %(message)s",
        )
        log = logging.getLogger("acceleration.scripts.detect_inflection")

    # ------------------------------------------------------------------
    # Phase 1: choose the data source.
    # ------------------------------------------------------------------
    if args.commits_jsonl.exists() and args.commits_jsonl.stat().st_size > 0:
        log.info(
            "Loading commits from %s",
            args.commits_jsonl,
            extra={"source": "jsonl", "path": str(args.commits_jsonl)},
        )
        commits = list(iter_commits_from_jsonl(args.commits_jsonl))
    else:
        ref = _resolve_live_git_ref(args.repo_root, args.branch)
        log.info(
            "commits.jsonl absent; falling back to live `git log` on ref=%s",
            ref,
            extra={"source": "git", "ref": ref, "repo_root": str(args.repo_root)},
        )
        commits = list(iter_commits_from_git(args.repo_root, ref))

    # ------------------------------------------------------------------
    # Phase 2: handle the empty-history edge case.
    # ------------------------------------------------------------------
    if not commits:
        result: dict[str, Any] = {
            "found": False,
            "value": "Insufficient signal — no commits available",
            "method": None,
            "candidates": {"A": None, "B": None},
            "needed": (
                "A populated git history or commits.jsonl produced by "
                "extract_git.py."
            ),
        }
        try:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(
                json.dumps(result, indent=2, default=str),
                encoding="utf-8",
            )
        except OSError as exc:
            log.error(
                "Failed to write output: %s",
                exc,
                extra={"output_path": str(args.output)},
            )
            return 1
        log.warning(
            "No commits available; wrote Insufficient-signal result.",
            extra={"output_path": str(args.output)},
        )
        return 0

    # ------------------------------------------------------------------
    # Phase 3: compute candidates and select.
    # ------------------------------------------------------------------
    log.info(
        "Loaded %d commits; computing candidates.",
        len(commits),
        extra={"commit_count": len(commits)},
    )
    cand_a = find_candidate_a(commits)
    counts = daily_commit_counts(commits)
    series = rolling_velocity_series(counts)
    cand_b = find_candidate_b(series)
    log.info(
        "Candidate A: %s",
        cand_a["date"] if cand_a else "none",
        extra={"candidate": "A", "date": cand_a["date"] if cand_a else None},
    )
    log.info(
        "Candidate B: %s",
        cand_b["date"] if cand_b else "none",
        extra={"candidate": "B", "date": cand_b["date"] if cand_b else None},
    )

    result = select_inflection(cand_a, cand_b)

    # Attach summary statistics about the velocity series so the
    # Methodology section of the report can describe the data envelope
    # the algorithm was operating over.
    result["velocity_series_summary"] = {
        "window_days": ROLLING_WINDOW_DAYS,
        "window_count": len(series),
        "first_window": series[0][0].isoformat() if series else None,
        "last_window": series[-1][0].isoformat() if series else None,
        "max_window_count": max((s[1] for s in series), default=0),
    }
    result["params"] = {
        "rolling_window_days": ROLLING_WINDOW_DAYS,
        "inflection_sigma": INFLECTION_SIGMA,
        "min_run_windows": INFLECTION_MIN_RUN_WINDOWS,
        "convergence_horizon_days": CONVERGENCE_HORIZON_DAYS,
    }

    # ------------------------------------------------------------------
    # Phase 4: persist the result.
    # ------------------------------------------------------------------
    try:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(
            json.dumps(result, indent=2, default=str),
            encoding="utf-8",
        )
    except OSError as exc:
        log.error(
            "Failed to write output: %s",
            exc,
            extra={"output_path": str(args.output)},
        )
        return 1

    if result["found"]:
        log.info(
            "Inflection date: %s  method=%s",
            result["date"],
            result["method"],
            extra={
                "inflection_date": result["date"],
                "method": result["method"],
                "chosen_candidate": result.get("chosen_candidate"),
                "output_path": str(args.output),
            },
        )
    else:
        log.warning(
            result["value"],
            extra={"output_path": str(args.output)},
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())

